import { useMemo, useState } from "react";
import {
  Activity,
  BarChart3,
  CalendarDays,
  CheckCircle2,
  Clock3,
  Download,
  Eye,
  FileBarChart,
  FileSpreadsheet,
  RefreshCcw,
  Search,
  ShieldAlert,
  ShieldCheck,
  TrendingUp,
  Users,
  X,
  XCircle,
  Filter,
  Trash2,
} from "lucide-react";

export default function Reports() {
  const [dateFilter, setDateFilter] = useState("Last 30 Days");
  const [search, setSearch] = useState("");
  const [selectedReport, setSelectedReport] = useState(null);
  const [activitiesVisible, setActivitiesVisible] = useState(true);
  const [lastUpdated, setLastUpdated] = useState("Just now");
  const [typeFilter, setTypeFilter] = useState("All");

  const stats = [
    { title: "Total Users", value: "12,480", growth: "+12%", positive: true, icon: <Users size={24} />, color: "blue" },
    { title: "Verified Staff", value: "10,942", growth: "+8%", positive: true, icon: <ShieldCheck size={24} />, color: "green" },
    { title: "Pending Reviews", value: "1,128", growth: "-4%", positive: false, icon: <Clock3 size={24} />, color: "yellow" },
    { title: "Rejected Requests", value: "410", growth: "+2%", positive: false, icon: <XCircle size={24} />, color: "red" },
  ];

  const reports = [
    {
      title: "Monthly Verification Report",
      desc: "Overview of approved, pending, and rejected healthcare staff registrations.",
      type: "PDF",
      updated: "2 hours ago",
      fileName: "monthly-verification-report.pdf",
      color: "blue",
    },
    {
      title: "Hospital Activity Analytics",
      desc: "Detailed analytics for staff registrations and hospital-level activity.",
      type: "Excel",
      updated: "Today",
      fileName: "hospital-activity-analytics.xlsx",
      color: "emerald",
    },
    {
      title: "Security Audit Report",
      desc: "Authentication logs, QR scans, and suspicious access attempts.",
      type: "PDF",
      updated: "Yesterday",
      fileName: "security-audit-report.pdf",
      color: "purple",
    },
  ];

  const activities = [
    { title: "Doctor verification approved", time: "5 mins ago", status: "success" },
    { title: "New pharmacy registration pending", time: "15 mins ago", status: "warning" },
    { title: "Unauthorized QR scan blocked", time: "1 hour ago", status: "danger" },
    { title: "Hospital analytics generated", time: "2 hours ago", status: "info" },
  ];

  const chartData = {
    "Last 7 Days":  [42, 58, 64, 71, 68, 82, 94],
    "Last 30 Days": [40, 55, 62, 70, 66, 80, 92],
    "Last 90 Days": [35, 49, 59, 74, 79, 88, 96],
    "This Year":    [30, 44, 57, 69, 78, 86, 98],
  };

  const filteredReports = useMemo(() => {
    const value = search.toLowerCase().trim();
    return reports.filter((report) => {
      const matchesSearch =
        report.title.toLowerCase().includes(value) ||
        report.desc.toLowerCase().includes(value) ||
        report.type.toLowerCase().includes(value);
      const matchesType = typeFilter === "All" || report.type === typeFilter;
      return matchesSearch && matchesType;
    });
  }, [search, typeFilter]);

  const handleExportFullReport = () => {
    const content = [
      "AI HealthVerify - Full System Report",
      "====================================",
      "",
      `Date Filter: ${dateFilter}`,
      `Report Type Filter: ${typeFilter}`,
      `Last Updated: ${lastUpdated}`,
      "",
      "Statistics:",
      ...stats.map((item) => `${item.title}: ${item.value} (${item.growth})`),
      "",
      "Reports:",
      ...filteredReports.map((r) => `${r.title} | ${r.type} | Updated: ${r.updated}`),
      "",
      "Recent Activities:",
      ...activities.map((a) => `${a.title} | ${a.time} | ${a.status}`),
    ].join("\n");
    downloadTextFile("full-healthverify-report.txt", content);
  };

  const handleDownloadReport = (report) => {
    const content = [
      `AI HealthVerify - ${report.title}`,
      "====================================",
      "",
      `Type: ${report.type}`,
      `Updated: ${report.updated}`,
      "",
      report.desc,
      "",
      "Generated by AI HealthVerify Admin Reports Center.",
    ].join("\n");
    downloadTextFile(report.fileName.replace(/\.(pdf|xlsx)$/i, ".txt"), content);
  };

  const handleRefresh = () => setLastUpdated(new Date().toLocaleTimeString());

  const handleClearFilters = () => {
    setSearch("");
    setTypeFilter("All");
    setDateFilter("Last 30 Days");
  };

  return (
    <div className="relative p-8 max-w-[1600px] mx-auto animate-fade-in overflow-hidden">
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl pointer-events-none" />

      <div className="relative z-10">
        {/* ─── Header ──────────────────────────────────────────── */}
        <header className="flex flex-col xl:flex-row xl:items-center xl:justify-between gap-6 mb-10">
          <div>
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-300 text-sm mb-4">
              <BarChart3 size={14} />
              Analytics & Reporting Center
            </div>
            <h1 className="text-4xl font-black text-white mb-3">Reports Dashboard</h1>
            <p className="text-slate-400">
              Monitor healthcare verification analytics, activity reports, approvals, and security insights.
            </p>
            <p className="text-xs text-slate-500 mt-3">Last updated: {lastUpdated}</p>
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={handleRefresh}
              className="h-12 px-5 rounded-2xl bg-white/5 border border-white/10 text-white font-bold hover:bg-white/10 transition flex items-center justify-center gap-2"
            >
              <RefreshCcw size={16} />
              Refresh
            </button>
            <button
              onClick={handleExportFullReport}
              className="h-12 px-5 rounded-2xl bg-gradient-to-r from-purple-500 to-blue-500 text-white font-bold hover:opacity-90 transition flex items-center justify-center gap-2"
            >
              <Download size={16} />
              Export Full Report
            </button>
          </div>
        </header>

        {/* ─── Stat Cards ──────────────────────────────────────── */}
        <div className="grid grid-cols-2 xl:grid-cols-4 gap-5 mb-10">
          {stats.map((item, i) => (
            <StatCard key={i} {...item} />
          ))}
        </div>

        {/* ─── Analytics + Activity Grid ───────────────────────── */}
        <div className="grid xl:grid-cols-3 gap-8 mb-10">
          {/* Chart */}
          <div className="xl:col-span-2 rounded-[2rem] border border-white/10 bg-slate-900/70 backdrop-blur-xl shadow-2xl p-8">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5 mb-8">
              <div>
                <h2 className="text-2xl font-black text-white flex items-center gap-2 mb-1">
                  <TrendingUp size={22} className="text-purple-400" />
                  Verification Analytics
                </h2>
                <p className="text-sm text-slate-500">
                  Healthcare verification performance overview
                </p>
              </div>
              <select
                value={dateFilter}
                onChange={(e) => setDateFilter(e.target.value)}
                className="h-10 px-4 rounded-xl bg-white/5 border border-white/10 text-sm text-slate-300 outline-none focus:border-purple-500/40 transition"
              >
                <option className="bg-slate-900">Last 7 Days</option>
                <option className="bg-slate-900">Last 30 Days</option>
                <option className="bg-slate-900">Last 90 Days</option>
                <option className="bg-slate-900">This Year</option>
              </select>
            </div>

            {/* Bar Chart */}
            <div className="relative h-[320px] rounded-2xl border border-white/10 bg-white/[0.02] p-6 overflow-hidden">
              <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 to-blue-500/5 pointer-events-none" />
              <div className="relative z-10 h-full flex items-end justify-between gap-3">
                {chartData[dateFilter].map((height, index) => {
                  const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
                  return (
                    <div key={index} className="flex-1 flex flex-col items-center gap-2">
                      <span className="text-xs font-black text-white/60 mb-1">{height}%</span>
                      <button
                        onClick={() => alert(`${days[index]} verification score: ${height}%`)}
                        title={`${height}% verification`}
                        className="w-full rounded-t-2xl transition-all hover:opacity-80 hover:scale-105 cursor-pointer"
                        style={{
                          height: `${(height / 100) * 220}px`,
                          background: `linear-gradient(to top, #8b5cf6, #3b82f6)`,
                          boxShadow: "0 0 20px rgba(139,92,246,0.25)",
                          minHeight: "40px",
                        }}
                      />
                      <span className="text-xs text-slate-500 font-bold">{days[index]}</span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          {/* Activity Log */}
          <div className="rounded-[2rem] border border-white/10 bg-slate-900/70 backdrop-blur-xl shadow-2xl p-6">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-black text-white flex items-center gap-2">
                <Activity size={20} className="text-blue-400" />
                Activity Logs
              </h2>
              <button
                onClick={() => setActivitiesVisible((v) => !v)}
                className="text-xs px-3 py-1.5 rounded-xl bg-white/5 border border-white/10 text-slate-300 hover:bg-white/10 transition font-bold"
              >
                {activitiesVisible ? "Hide" : "Show"}
              </button>
            </div>

            {activitiesVisible ? (
              <div className="space-y-3">
                {activities.map((activity, i) => (
                  <ActivityItem key={i} {...activity} />
                ))}
              </div>
            ) : (
              <div className="rounded-2xl bg-white/[0.03] border border-white/[0.06] p-5 text-center">
                <p className="text-sm text-slate-500">Activity logs are hidden.</p>
              </div>
            )}

            {/* Security summary */}
            <div className="mt-6 pt-6 border-t border-white/10 space-y-3">
              <SecurityRow icon={<ShieldCheck size={16} />} title="System Security" value="Protected" color="emerald" />
              <SecurityRow icon={<ShieldAlert size={16} />} title="Threat Detection" value="Active" color="yellow" />
              <SecurityRow icon={<CheckCircle2 size={16} />} title="Accuracy" value="98.7%" color="blue" />
            </div>
          </div>
        </div>

        {/* ─── Reports List ─────────────────────────────────────── */}
        <div className="rounded-[2rem] border border-white/10 bg-slate-900/70 backdrop-blur-xl shadow-2xl overflow-hidden">
          <div className="p-8 border-b border-white/10 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5">
            <div>
              <h2 className="text-2xl font-black text-white flex items-center gap-2 mb-1">
                <FileBarChart size={22} className="text-purple-400" />
                Generated Reports
              </h2>
              <p className="text-slate-500 text-sm">
                Exportable reports for hospital management.
              </p>
            </div>

            <div className="flex flex-col sm:flex-row gap-3 w-full lg:w-auto">
              <div className="relative w-full lg:w-72">
                <Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" />
                <input
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  placeholder="Search reports…"
                  className="w-full h-12 rounded-2xl bg-white/5 border border-white/10 pl-11 pr-4 text-white outline-none focus:border-purple-500/40 transition"
                />
              </div>
              <select
                value={typeFilter}
                onChange={(e) => setTypeFilter(e.target.value)}
                className="h-12 px-4 rounded-2xl bg-white/5 border border-white/10 text-slate-300 outline-none focus:border-purple-500/40 transition"
              >
                <option className="bg-slate-900">All</option>
                <option className="bg-slate-900">PDF</option>
                <option className="bg-slate-900">Excel</option>
              </select>
              <button
                onClick={handleClearFilters}
                className="h-12 px-4 rounded-2xl bg-white/5 border border-white/10 text-white font-bold hover:bg-white/10 transition flex items-center justify-center gap-2"
              >
                <Trash2 size={15} />
                Clear
              </button>
            </div>
          </div>

          <div className="divide-y divide-white/[0.05]">
            {filteredReports.length === 0 ? (
              <div className="p-12 text-center text-slate-500">No reports match your search.</div>
            ) : (
              filteredReports.map((report, i) => (
                <ReportRow
                  key={i}
                  report={report}
                  onView={() => setSelectedReport(report)}
                  onDownload={() => handleDownloadReport(report)}
                />
              ))
            )}
          </div>
        </div>
      </div>

      {/* ─── Report Modal ─────────────────────────────────────── */}
      {selectedReport && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-xl rounded-[2rem] bg-slate-950 border border-white/10 shadow-2xl overflow-hidden">
            <div className="p-6 border-b border-white/10 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400">
                  <FileBarChart size={18} />
                </div>
                <h2 className="text-xl font-black text-white">Report Details</h2>
              </div>
              <button
                onClick={() => setSelectedReport(null)}
                className="w-9 h-9 rounded-xl bg-white/5 hover:bg-white/10 flex items-center justify-center transition text-slate-400"
              >
                <X size={16} />
              </button>
            </div>
            <div className="p-6 space-y-3">
              <Detail label="Title" value={selectedReport.title} />
              <Detail label="Type" value={selectedReport.type} />
              <Detail label="Last Updated" value={selectedReport.updated} />
              <Detail label="Description" value={selectedReport.desc} />
              <button
                onClick={() => handleDownloadReport(selectedReport)}
                className="w-full h-12 rounded-2xl bg-purple-500 hover:bg-purple-400 text-white font-black transition flex items-center justify-center gap-2"
              >
                <Download size={16} />
                Download This Report
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function ReportRow({ report, onView, onDownload }) {
  const typeColors = {
    PDF: "bg-blue-500/10 border-blue-500/20 text-blue-400",
    Excel: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
  };

  return (
    <div className="p-8 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6 hover:bg-white/[0.02] transition">
      <div className="flex items-start gap-5">
        <div className={`w-14 h-14 rounded-2xl border flex items-center justify-center flex-shrink-0 ${typeColors[report.type] || "bg-purple-500/10 border-purple-500/20 text-purple-400"}`}>
          {report.type === "PDF" ? <FileBarChart size={26} /> : <FileSpreadsheet size={26} />}
        </div>
        <div>
          <h3 className="text-xl font-black text-white mb-2">{report.title}</h3>
          <p className="text-slate-400 text-sm mb-3 max-w-2xl leading-relaxed">{report.desc}</p>
          <div className="flex items-center gap-3 text-xs text-slate-500 font-semibold">
            <span className={`px-2.5 py-1 rounded-lg border font-black ${typeColors[report.type] || ""}`}>
              {report.type}
            </span>
            <span>Updated {report.updated}</span>
          </div>
        </div>
      </div>
      <div className="flex gap-3 flex-shrink-0">
        <button
          onClick={onView}
          className="h-11 px-5 rounded-2xl bg-white/5 border border-white/10 text-white font-bold hover:bg-white/10 transition flex items-center gap-2 text-sm"
        >
          <Eye size={16} />
          View
        </button>
        <button
          onClick={onDownload}
          className="h-11 px-5 rounded-2xl bg-purple-500/10 border border-purple-500/20 text-purple-300 font-bold hover:bg-purple-500/20 transition flex items-center gap-2 text-sm"
        >
          <Download size={16} />
          Download
        </button>
      </div>
    </div>
  );
}

function StatCard({ title, value, growth, positive, icon, color }) {
  const styles = {
    blue: "bg-blue-500/10 border-blue-500/20 text-blue-400",
    green: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
    yellow: "bg-amber-500/10 border-amber-500/20 text-amber-400",
    red: "bg-red-500/10 border-red-500/20 text-red-400",
  };

  return (
    <div className="rounded-3xl border border-white/10 bg-slate-900/70 backdrop-blur-xl shadow-xl p-6 hover:-translate-y-1 transition">
      <div className={`w-12 h-12 rounded-2xl border flex items-center justify-center mb-4 ${styles[color]}`}>
        {icon}
      </div>
      <p className="text-xs text-slate-500 font-black uppercase tracking-widest mb-2">{title}</p>
      <h3 className="text-4xl font-black text-white mb-3">{value}</h3>
      <span className={`text-xs font-black px-2.5 py-1 rounded-lg ${positive ? "bg-emerald-500/10 text-emerald-400" : "bg-red-500/10 text-red-400"}`}>
        {growth} this month
      </span>
    </div>
  );
}

function ActivityItem({ title, time, status }) {
  const cfg = {
    success: { dot: "bg-emerald-400", bg: "hover:bg-emerald-500/5" },
    warning: { dot: "bg-amber-400", bg: "hover:bg-amber-500/5" },
    danger:  { dot: "bg-red-400", bg: "hover:bg-red-500/5" },
    info:    { dot: "bg-blue-400", bg: "hover:bg-blue-500/5" },
  };
  const style = cfg[status] || cfg.info;

  return (
    <div className={`flex gap-3 p-3 rounded-2xl bg-white/[0.03] border border-white/[0.06] transition ${style.bg}`}>
      <div className={`w-2.5 h-2.5 rounded-full mt-2 flex-shrink-0 ${style.dot}`} />
      <div>
        <p className="text-sm font-bold text-white leading-snug">{title}</p>
        <p className="text-xs text-slate-500 mt-0.5">{time}</p>
      </div>
    </div>
  );
}

function SecurityRow({ icon, title, value, color }) {
  const colors = {
    emerald: "text-emerald-400",
    yellow: "text-amber-400",
    blue: "text-blue-400",
  };

  return (
    <div className="flex items-center justify-between rounded-xl bg-white/[0.03] border border-white/[0.06] px-4 py-2.5">
      <div className="flex items-center gap-2 text-slate-400 text-sm">
        {icon}
        {title}
      </div>
      <span className={`text-sm font-black ${colors[color] || "text-white"}`}>{value}</span>
    </div>
  );
}

function Detail({ label, value }) {
  return (
    <div className="rounded-2xl bg-white/5 border border-white/10 p-4">
      <p className="text-xs text-slate-500 font-black uppercase tracking-widest mb-1.5">{label}</p>
      <p className="text-white font-semibold">{value}</p>
    </div>
  );
}

function downloadTextFile(fileName, content) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  link.click();
  URL.revokeObjectURL(url);
}