import { useEffect, useMemo, useState } from "react";
import { collection, getDocs } from "firebase/firestore";

import {
  AlertTriangle,
  Brain,
  CheckCircle2,
  Clipboard,
  Download,
  Eye,
  FileCheck,
  FileSearch,
  RotateCcw,
  ScanLine,
  ShieldCheck,
  Sparkles,
  Trash2,
  Upload,
  X,
  RefreshCcw,
  Smartphone,
  Clock,
  CheckCircle,
  XCircle,
  UserCheck,
  UserX,
} from "lucide-react";

import { db } from "../config/firebase";
import SuccessAlert from "../components/Common/SuccessAlert";
import ErrorAlert from "../components/Common/ErrorAlert";

/* ─────────────────────────────────────────────────────────────────────────────
   SINGLE SOURCE OF TRUTH NOTE — same rule as PendingVerifications.jsx
   ─────────────────────────────────────────────────────────────────────────────
   Flask / ai_service.py is the ONLY place that computes riskLevel and
   recommendation (see _build_decision: confidence>=75 & documentConfidence>=75
   -> approve/low; confidence>=55 -> manual_review/medium; else -> reject/high).

   This page used to run its own OCR (tesseract.js) and its own independent
   scoring (85/65/45 thresholds) to produce a SECOND, competing decision.
   That has been removed. This project uses:
- DeepFace for face verification
- Tesseract OCR for document text extraction

OCR is executed in ai_service.py and the results are stored in Firestore.
This page does not run OCR itself; it only displays OCR results already
generated by the Flask backend.because the AI
   service only does face-matching, not document text/authenticity analysis.

   This page now only PREVIEWS a document file for the admin and DISPLAYS the
   already-computed Flask result for the most recently submitted user record,
   exactly the way ApprovedDoctors/PendingDoctors/PendingVerifications do.
   ───────────────────────────────────────────────────────────────────────────── */

function getRiskLevel(mobileAiResult) {
  const stored = (mobileAiResult?.riskLevel || "").toLowerCase();

  if (stored === "low" || stored === "low risk") {
    return { label: "Low Risk", value: "low", color: "teal", icon: <ShieldCheck size={18} /> };
  }
  if (stored === "medium" || stored === "medium risk") {
    return { label: "Medium Risk", value: "medium", color: "amber", icon: <Clock size={18} /> };
  }
  if (stored === "high" || stored === "high risk") {
    return { label: "High Risk", value: "high", color: "red", icon: <AlertTriangle size={18} /> };
  }

  // Fallback only for legacy records missing riskLevel — same thresholds as
  // ai_service.py's _build_decision, never anything stricter/looser.
  const faceConfidence = Number(mobileAiResult?.confidence || 0);
  const documentConfidence = Number(mobileAiResult?.documentConfidence || 0);
  const faceMatch = mobileAiResult?.faceMatch === true;

  if (faceMatch && faceConfidence >= 75 && documentConfidence >= 75) {
    return { label: "Low Risk", value: "low", color: "teal", icon: <ShieldCheck size={18} /> };
  }
  if (faceConfidence >= 55) {
    return { label: "Medium Risk", value: "medium", color: "amber", icon: <Clock size={18} /> };
  }
  return { label: "High Risk", value: "high", color: "red", icon: <AlertTriangle size={18} /> };
}

function getRecommendation(mobileAiResult) {
  if (!mobileAiResult) {
    return {
      label: "NO AI RESULT",
      color: "amber",
      description:
        "No mobile/web AI verification result has been loaded from Firestore yet. Refresh once a user has submitted documents.",
    };
  }

  const stored = (mobileAiResult.verificationRecommendation || "").toLowerCase();
  const faceConfidence = Number(mobileAiResult.confidence || 0);
  const documentConfidence = Number(mobileAiResult.documentConfidence || 0);

  if (stored === "approve" || stored === "recommended approval") {
    return {
      label: "APPROVE",
      color: "teal",
      description:
        "Flask reported face match, document confidence, and AI confidence all at or above the 75% approval threshold.",
    };
  }

  if (stored === "reject" || stored === "recommended rejection") {
    return {
      label: "REJECT",
      color: "red",
      description: `Flask confidence is below the 55% reject threshold. Face: ${faceConfidence}%, Document: ${documentConfidence}%.`,
    };
  }

  if (stored === "manual_review" || stored === "manual review" || stored === "manual review required") {
    return {
      label: "MANUAL REVIEW",
      color: "amber",
      description: `Flask confidence is between 55–74% (Face: ${faceConfidence}%, Document: ${documentConfidence}%). Admin review needed.`,
    };
  }

  // Fallback for legacy records — same thresholds as ai_service.py.
  if (mobileAiResult.faceMatch === true && faceConfidence >= 75 && documentConfidence >= 75) {
    return {
      label: "APPROVE",
      color: "teal",
      description: "AI confidence and face match passed Flask thresholds (≥ 75%).",
    };
  }
  if (faceConfidence >= 55) {
    return {
      label: "MANUAL REVIEW",
      color: "amber",
      description: `Face confidence ${faceConfidence}% is between 55–74%. Admin review needed.`,
    };
  }
  return {
    label: "REJECT",
    color: "red",
    description: `Face confidence ${faceConfidence}% is below the Flask reject threshold (< 55%).`,
  };
}

function getFinalStatus(recommendationLabel) {
  if (recommendationLabel === "APPROVE") return "verified";
  if (recommendationLabel === "REJECT") return "rejected";
  return "pending review";
}

export default function VerifyDocuments() {
  const [file, setFile] = useState(null);
  const [filePreviewURL, setFilePreviewURL] = useState("");

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [mobileAiResult, setMobileAiResult] = useState(null);
  const [firebaseLoading, setFirebaseLoading] = useState(false);
  const [error, setError] = useState("");

  const [documentType, setDocumentType] = useState("Medical ID");
  const [dragActive, setDragActive] = useState(false);
  const [mounted, setMounted] = useState(false);

  const acceptedTypes = ["image/jpeg", "image/png", "image/jpg", "application/pdf"];

  const fileSize = useMemo(() => {
    if (!file) return "";
    return `${(file.size / 1024 / 1024).toFixed(2)} MB`;
  }, [file]);

  const fetchLatestMobileAiResult = async () => {
    setFirebaseLoading(true);
    setError("");

    try {
      const usersRef = collection(db, "users");
      const snap = await getDocs(usersRef);

      if (snap.empty) {
        setMobileAiResult(null);
        setError("No users found in Firestore.");
        return;
      }

      const users = snap.docs
        .map((docSnap) => ({
          id: docSnap.id,
          ...docSnap.data(),
        }))
        .filter((u) => u.documentsUploaded === true)
        .sort((a, b) => {
          const aTime = a.updatedAt?.seconds || 0;
          const bTime = b.updatedAt?.seconds || 0;
          return bTime - aTime;
        });

      if (users.length === 0) {
        setMobileAiResult(null);
        setError("No uploaded AI result found yet.");
        return;
      }

      const data = users[0];

      setMobileAiResult({
        id: data.id,
        name: data.name || "Healthcare Staff",
        email: data.email || "No email",
        role: data.role || "Staff",

        status: data.status || "pending",
        verificationStatus: data.verificationStatus || "pending",

        faceMatch: data.faceMatch === true,
        confidence: Number(data.confidence || 0),
        aiScore: Number(data.aiScore || 0),

        documentConfidence: Number(data.documentConfidence || 0),

        aiProcessingStatus: data.aiProcessingStatus || "pending",
        faceMatchStatus: data.faceMatchStatus || "pending",

        ocrStatus: data.ocrStatus || "not_processed",
        // FIX: this previously read `mobileAiResult?.documentText`, which is
        // the *old* React state value (stale closure), not the record we
        // just fetched from Firestore. That meant this field almost always
        // fell back to "No text extracted" even when Tesseract OCR (run in
        // ai_service.py) successfully extracted text. It now reads from
        // `data`, the freshly-fetched Firestore document, like every other
        // field here.
        documentText: data.documentText || "No text extracted",
        documentOcrConfidence: Number(data.documentOcrConfidence || 0),
        documentOcrWordCount: Number(data.documentOcrWordCount || 0),
        documentCandidateIds: data.documentCandidateIds || [],

        documentCheckStatus: data.documentCheckStatus || "failed",

        deepFaceDistance: Number(data.deepFaceDistance || 0),
        deepFaceModel: data.deepFaceModel || "Facenet",
        deepFaceDetector: data.deepFaceDetector || "opencv",

        riskLevel: data.riskLevel || "",

        verificationRecommendation: data.recommendation || "",

        documentURL: data.documentURL || "",
        selfieURL: data.selfieURL || "",

        documentLocalPath: data.documentLocalPath || "",
        selfieLocalPath: data.selfieLocalPath || "",

        updatedAt: data.updatedAt,
      });
    } catch (err) {
      console.error(err);
      setError("Authentication Error: Could not load AI result from Firestore.");
    } finally {
      setFirebaseLoading(false);
    }
  };

  useEffect(() => {
    setMounted(true);
    fetchLatestMobileAiResult();

    return () => {
      if (filePreviewURL) {
        URL.revokeObjectURL(filePreviewURL);
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const validateFile = (selected) => {
    if (!selected) return "";

    if (!acceptedTypes.includes(selected.type)) {
      return "Invalid file type. Please upload PDF, JPG, or PNG.";
    }

    if (selected.size > 5 * 1024 * 1024) {
      return "File size must be less than 5MB.";
    }

    return "";
  };

  const setSelectedFile = (selected) => {
    const validationError = validateFile(selected);

    if (validationError) {
      setError(validationError);
      return;
    }

    if (filePreviewURL) {
      URL.revokeObjectURL(filePreviewURL);
    }

    setFile(selected);
    setFilePreviewURL(URL.createObjectURL(selected));
    setResult(null);
    setError("");
  };

  const handleFileChange = (e) => {
    const selected = e.target.files?.[0];

    if (selected) {
      setSelectedFile(selected);
    }

    e.target.value = "";
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setDragActive(false);

    const selected = e.dataTransfer.files?.[0];

    if (selected) {
      setSelectedFile(selected);
    }
  };

  const handleClearFile = () => {
    if (filePreviewURL) {
      URL.revokeObjectURL(filePreviewURL);
    }

    setFile(null);
    setFilePreviewURL("");
    setResult(null);
    setError("");
  };

  const handlePreview = () => {
    if (!filePreviewURL) {
      setError("Please select a file first.");
      return;
    }

    window.open(filePreviewURL, "_blank", "noopener,noreferrer");
  };

  // OCR and face verification are already computed by ai_service.py.
  // This page only displays the stored Firestore result. This just packages
  // the already-computed Flask result (mobileAiResult) into the same result
  // shape the UI expects, alongside the locally selected file for
  // preview/record purposes.
  const handleVerify = async () => {
    if (!file) {
      setError("Please select a document first.");
      return;
    }

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const recommendation = getRecommendation(mobileAiResult);
      const riskLevel = getRiskLevel(mobileAiResult);
      const finalStatus = getFinalStatus(recommendation.label);
      const fraudDetected = recommendation.label !== "APPROVE";

      const checklist = [
        {
          label: "Document file selected for review",
          passed: true,
          note: `${file.name} (${fileSize})`,
        },
        {
          label: "AI verification result loaded from Firestore",
          passed: Boolean(mobileAiResult),
          note: mobileAiResult
            ? `Loaded for ${mobileAiResult.name}`
            : "No AI result found — refresh after a user submits documents",
        },
        {
          label: "Face match passed (Flask / DeepFace)",
          passed: mobileAiResult?.faceMatch === true,
          note: mobileAiResult ? `${mobileAiResult.confidence}% confidence` : "No result loaded",
        },
        {
          label: "Tesseract OCR completed",
          passed: mobileAiResult?.ocrStatus === "completed",
          note: mobileAiResult
            ? `${mobileAiResult.documentOcrWordCount} words detected`
            : "No OCR result",
        },
        {
          label: "Flask recommendation meets approval threshold",
          passed: recommendation.label === "APPROVE",
          note: recommendation.description,
        },
      ];

      setResult({
        status: finalStatus,
        confidence: Number(mobileAiResult?.documentConfidence || 0),
        aiScore: Number(mobileAiResult?.aiScore || 0),
        fraudDetected,
        documentType,
        fileName: file.name,
        fileSize,
        decisionLabel:
          finalStatus === "verified"
            ? "Verified"
            : finalStatus === "rejected"
            ? "Rejected / Invalid"
            : "Pending Human Review",
        recommendation,
        riskLevel,
        checklist,
        extractedData: {
          documentFileSelected: file.name,
          documentTypeSelected: documentType,
          mobileAiRecordLoaded: mobileAiResult
            ? `${mobileAiResult.name} (${mobileAiResult.email})`
            : "None loaded",
          faceMatch:
            mobileAiResult?.faceMatch === true
              ? `Passed (${mobileAiResult.confidence}%)`
              : mobileAiResult
              ? "Failed or pending"
              : "No AI result loaded",
          aiScore: mobileAiResult ? `${mobileAiResult.aiScore}%` : "N/A",
          documentConfidence: mobileAiResult ? `${mobileAiResult.documentConfidence}%` : "N/A",
          riskLevel: riskLevel.label,
          flaskRecommendation: recommendation.label,
          ocrStatus: mobileAiResult?.ocrStatus || "Unknown",

          documentOcrConfidence: mobileAiResult
            ? `${mobileAiResult.documentOcrConfidence}%`
            : "N/A",

          documentOcrWordCount: mobileAiResult
            ? mobileAiResult.documentOcrWordCount
            : "N/A",

          // Added so the admin can actually see the OCR text that Tesseract
          // extracted, instead of it only being fetched and never shown.
          documentText: mobileAiResult?.documentText || "No text extracted",

          candidateIds:
            mobileAiResult?.documentCandidateIds?.join(", ") || "None",
          lastUpdated: mobileAiResult?.updatedAt?.seconds
            ? new Date(mobileAiResult.updatedAt.seconds * 1000).toLocaleString()
            : "N/A",
        },
        aiChecks: {
          documentIntelligence: mobileAiResult
            ? `OCR Completed (${mobileAiResult.documentOcrWordCount} words, ${mobileAiResult.documentOcrConfidence}% confidence)`
            : "No OCR result loaded",
          faceMatch: mobileAiResult?.faceMatch
            ? `Passed from Flask/DeepFace (${mobileAiResult.confidence}%)`
            : mobileAiResult
            ? "Failed or pending from Flask/DeepFace"
            : "No AI result loaded",
          forgery: "Not automated — requires manual admin review of the document image.",
          registry: mobileAiResult ? "Connected to Firestore" : "Not connected",
        },
        message:
          finalStatus === "verified"
            ? "Flask-reported result meets the approval threshold. Admin can confirm after reviewing the document."
            : finalStatus === "rejected"
            ? "Flask-reported result is below the reject threshold. Manual override is possible from the user's profile."
            : "Flask-reported result requires manual admin review before approval.",
      });
    } catch (err) {
      console.error(err);
      setError("Could not build the verification summary. Please refresh and try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setResult(null);
    setError("");
  };

  const handleCopyResult = async () => {
    if (!result) {
      setError("No verification result to copy.");
      return;
    }

    try {
      await navigator.clipboard.writeText(JSON.stringify(result, null, 2));
      setError("");
    } catch {
      setError("Copy failed. Please try again.");
    }
  };

  const handleDownloadResult = () => {
    if (!result) {
      setError("No verification result to download.");
      return;
    }

    const content = [
      "AI HealthVerify - Document Verification Result",
      "================================================",
      "",
      `Document Type: ${result.documentType}`,
      `File Name: ${result.fileName}`,
      `File Size: ${result.fileSize}`,
      `Status: ${result.status}`,
      `Final Decision: ${result.decisionLabel}`,
      `AI Recommendation: ${result.recommendation?.label || "N/A"}`,
      `Risk Level: ${result.riskLevel?.label || "N/A"}`,
      `Document Confidence: ${result.confidence}%`,
      `AI Score: ${result.aiScore}%`,
      `Admin Review Required: ${result.fraudDetected ? "Yes" : "No"}`,
      "",
      "Verification Checklist:",
      ...(result.checklist || []).map(
        (item) =>
          `${item.passed ? "[PASS]" : "[REVIEW]"} ${item.label}${
            item.note ? ` - ${item.note}` : ""
          }`
      ),
      "",
      "Extracted Data:",
      ...Object.entries(result.extractedData).map(([key, value]) => `${key}: ${value}`),
    ].join("\n");

    const blob = new Blob([content], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = "verification-result.txt";
    link.click();

    URL.revokeObjectURL(url);
  };

  return (
    <div className={`vd-root ${mounted ? "vd-mounted" : ""}`}>
      {/* ── Page header ── */}
      <header className="vd-page-header">
        <div className="vd-page-title-group">
          <div className="vd-page-eyebrow">
            <Brain size={14} />
            Document Preview + Flask Face Verification
          </div>

          <h1 className="vd-page-title">Verify Documents</h1>

          <p className="vd-page-sub">
            Preview a healthcare document and review the AI verification result
            already computed by the Flask/DeepFace backend and stored in
            Firestore. This project uses DeepFace face verification and Tesseract OCR document
            analysis. OCR results are generated by the Flask backend and displayed here
            for administrator review, so the result shown here always matches
            what admins see on the Pending Verifications page.
          </p>
        </div>

        <div className="vd-header-actions">
          <button onClick={fetchLatestMobileAiResult} className="vd-btn vd-btn-teal">
            <RefreshCcw size={16} className={firebaseLoading ? "vd-spin" : ""} />
            Refresh AI Result
          </button>

          <button onClick={handleReset} className="vd-btn vd-btn-ghost">
            <RotateCcw size={16} />
            Reset Result
          </button>

          <div className="vd-active-chip">
            <ShieldCheck size={15} />
            AI Review Active
          </div>
        </div>
      </header>

      {error && <ErrorAlert message={error} onClose={() => setError("")} />}
      {result && <SuccessAlert message={result.message} onClose={() => setResult(null)} />}

      {mobileAiResult && (
        <div className="vd-panel vd-mobile-panel">
          <div className="vd-mobile-row">
            <div className="vd-mobile-head">
              <div className="vd-mobile-icon">
                <Smartphone size={24} />
              </div>
              <div>
                <h2 className="vd-mobile-title">Latest AI Verification Result (Flask)</h2>
                <p className="vd-mobile-sub">
                  {mobileAiResult.name} • {mobileAiResult.role} • {mobileAiResult.email}
                </p>
              </div>
            </div>

            <div className="vd-mini-ai-grid">
              <MiniAICard title="AI Score" value={`${mobileAiResult.aiScore}%`} />
              <MiniAICard title="Confidence" value={`${mobileAiResult.confidence}%`} />
              <MiniAICard title="Face Match" value={mobileAiResult.faceMatch ? "Passed" : "Failed"} />
              <MiniAICard
                title="Risk Level"
                value={mobileAiResult.riskLevel || "Unknown"}
              />

              <MiniAICard
                title="OCR Status"
                value={mobileAiResult.ocrStatus || "Unknown"}
              />
            </div>
          </div>
        </div>
      )}

      <div className="vd-main-grid">
        {/* ── Upload panel ── */}
        <div className="vd-panel vd-upload-panel">
          <div className="vd-panel-head">
            <div className="vd-panel-head-icon vd-icon-blue">
              <Upload size={22} />
            </div>
            <div>
              <h2 className="vd-panel-title">Preview Document</h2>
              <p className="vd-panel-sub">Visually inspect the file alongside the Flask AI result</p>
            </div>
          </div>

          <div className="vd-field">
            <label className="vd-field-label">Document Type (record only)</label>
            <select
              value={documentType}
              onChange={(e) => {
                setDocumentType(e.target.value);
                setResult(null);
              }}
              className="vd-select"
            >
              <option>Medical ID</option>
              <option>Prescription</option>
              <option>Lab Report</option>
              <option>Insurance Card</option>
              <option>Health Certificate</option>
            </select>
          </div>

          <div
            onDragOver={(e) => {
              e.preventDefault();
              setDragActive(true);
            }}
            onDragLeave={() => setDragActive(false)}
            onDrop={handleDrop}
            className={`vd-dropzone ${dragActive ? "vd-dropzone-active" : ""}`}
          >
            <div className="vd-dropzone-icon">
              <Upload size={36} />
            </div>

            <h3 className="vd-dropzone-title">Drag &amp; Drop Document</h3>

            <p className="vd-dropzone-sub">
              Upload JPG, PNG, or PDF to preview alongside the stored AI result.
              OCR text extraction and DeepFace verification are performed by the Flask backend.
            </p>

            <input
              type="file"
              id="fileUpload"
              accept="image/*,.pdf"
              onChange={handleFileChange}
              className="vd-hidden-input"
            />

            <label htmlFor="fileUpload" className="vd-choose-btn">
              <Upload size={16} />
              Choose File
            </label>

            {file && (
              <div className="vd-file-card">
                <div className="vd-file-card-row">
                  <CheckCircle2 size={20} className="vd-file-card-check" />
                  <div className="vd-file-card-info">
                    <p className="vd-file-card-name">{file.name}</p>
                    <p className="vd-file-card-meta">Ready for review • {fileSize}</p>
                  </div>
                </div>

                <div className="vd-file-card-actions">
                  <button onClick={handlePreview} className="vd-mini-btn vd-mini-btn-blue">
                    <Eye size={15} />
                    Preview
                  </button>
                  <button onClick={handleClearFile} className="vd-mini-btn vd-mini-btn-red">
                    <Trash2 size={15} />
                    Remove
                  </button>
                </div>
              </div>
            )}
          </div>

          <button onClick={handleVerify} disabled={loading || !file} className="vd-verify-btn">
            {loading ? (
              <>
                <span className="vd-loader" />
                Building Verification Summary...
              </>
            ) : (
              <>
                <ScanLine size={18} />
                Show Verification Summary
              </>
            )}
          </button>
        </div>

        {/* ── Result panel ── */}
        <div className="vd-result-col">
          {result ? (
            <>
              <div className="vd-panel vd-result-panel">
                <div className="vd-result-head">
                  <div className="vd-result-head-left">
                    <div className="vd-result-head-icon">
                      <FileCheck size={28} />
                    </div>
                    <div>
                      <h2 className="vd-result-title">Verification Result</h2>
                      <p className="vd-result-sub">Sourced from Flask AI service</p>
                    </div>
                  </div>

                  <div className="vd-result-actions">
                    <button onClick={handleCopyResult} className="vd-icon-btn" title="Copy Result">
                      <Clipboard size={16} />
                    </button>
                    <button onClick={handleDownloadResult} className="vd-icon-btn" title="Download Result">
                      <Download size={16} />
                    </button>
                    <button onClick={() => setResult(null)} className="vd-icon-btn vd-icon-btn-red" title="Close Result">
                      <X size={16} />
                    </button>
                  </div>
                </div>

                <DecisionBanner status={result.status} label={result.decisionLabel} />

                <div className="vd-metric-row">
                  <MetricCard title="Document Confidence" value={`${result.confidence}%`} color="teal" />
                  <MetricCard title="Final AI Score" value={`${result.aiScore}%`} color="blue" />
                  <MetricCard title="Risk Level" value={result.riskLevel?.label || "N/A"} color={result.riskLevel?.color || "amber"} />
                </div>

                <RecommendationCard recommendation={result.recommendation} />

                <ChecklistCard checklist={result.checklist || []} />

                <div className={`vd-admin-box ${result.fraudDetected ? "vd-admin-warn" : "vd-admin-ok"}`}>
                  {result.fraudDetected ? (
                    <AlertTriangle size={22} />
                  ) : (
                    <ShieldCheck size={22} />
                  )}
                  <div>
                    <h3 className="vd-admin-title">Admin Review Decision</h3>
                    <p className="vd-admin-sub">
                      {result.fraudDetected
                        ? "Needs admin review before approval"
                        : "Meets the Flask approval threshold"}
                    </p>
                  </div>
                </div>

                <div className="vd-extracted-block">
                  <div className="vd-extracted-head">
                    <Sparkles size={20} color="#6AA3FF" />
                    <h3 className="vd-extracted-title">Verification Summary</h3>
                  </div>

                  <div className="vd-extracted-list">
                    {Object.entries(result.extractedData).map(([key, value]) => (
                      <button
                        key={key}
                        onClick={() => navigator.clipboard.writeText(String(value))}
                        className="vd-extracted-row"
                      >
                        <span className="vd-extracted-key">{key.replace(/([A-Z])/g, " $1")}</span>
                        <span className="vd-extracted-value">{value}</span>
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <div className="vd-panel vd-engine-panel">
                <div className="vd-engine-head">
                  <Brain size={32} color="#6AA3FF" />
                  <div>
                    <h2 className="vd-engine-title">AI Verification Engine</h2>
                    <p className="vd-engine-sub">Flask / DeepFace + Tesseract OCR verification result</p>
                  </div>
                </div>

                <div className="vd-ai-status-list">
                  <AIStatus title="Document Analysis" status={result.aiChecks.documentIntelligence} />
                  <AIStatus title="Face Match Analysis" status={result.aiChecks.faceMatch} />
                  <AIStatus title="Forgery Detection" status={result.aiChecks.forgery} />
                  <AIStatus title="Healthcare Registry Match" status={result.aiChecks.registry} />
                </div>
              </div>
            </>
          ) : (
            <div className="vd-panel vd-empty-panel">
              <div className="vd-empty-icon">
                <FileSearch size={42} />
              </div>
              <h2 className="vd-empty-title">Waiting for Verification</h2>
              <p className="vd-empty-sub">
                Select a document to preview, then show the stored Flask AI
                verification result for the most recent submission.
              </p>
            </div>
          )}
        </div>
      </div>

      {/* ── Styles ── */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Inter:wght@300;400;500;600;700;800&display=swap');

        .vd-root {
          --bg:          #060D1F;
          --surface:     #0D1733;
          --surface2:    #111E3A;
          --surface3:    #162040;
          --border:      rgba(255,255,255,0.065);
          --border2:     rgba(255,255,255,0.11);
          --blue:        #1D6EFF;
          --teal:        #00E5C3;
          --amber:       #F59E0B;
          --red:         #EF4444;
          --violet:      #8B5CF6;
          --text:        #E8EDF8;
          --muted:       #5A6A8A;
          --muted2:      #3D4F70;
          --r:           14px;
          --r-sm:        10px;
          --r-lg:        24px;
          --shadow:      0 4px 32px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.04);

          font-family: 'Inter', system-ui, sans-serif;
          color: var(--text);
          background: var(--bg);
          min-height: 100vh;
          padding: 2rem 2rem 3rem;
          max-width: 1600px;
          margin: 0 auto;
          position: relative;
          opacity: 0;
          transform: translateY(12px);
          transition: opacity 0.55s ease, transform 0.55s ease;
        }
        .vd-mounted { opacity: 1; transform: translateY(0); }
        .vd-root * { box-sizing: border-box; }

        /* ── Header ── */
        .vd-page-header {
          display: flex; flex-wrap: wrap; align-items: flex-start;
          justify-content: space-between; gap: 1.25rem; margin-bottom: 2.25rem;
        }
        .vd-page-title-group { max-width: 680px; }
        .vd-page-eyebrow {
          display: inline-flex; align-items: center; gap: 0.5rem;
          font-size: 0.75rem; font-weight: 600; color: #6AA3FF;
          background: rgba(29,110,255,0.1); border: 1px solid rgba(29,110,255,0.2);
          border-radius: 100px; padding: 0.5rem 1rem; margin-bottom: 1rem;
        }
        .vd-page-title {
          font-size: clamp(1.75rem, 3.4vw, 2.5rem); font-weight: 800;
          letter-spacing: -0.025em; color: var(--text); margin: 0 0 0.75rem;
        }
        .vd-page-sub { font-size: 0.9375rem; color: var(--muted); margin: 0; line-height: 1.55; }

        .vd-header-actions { display: flex; flex-direction: column; gap: 0.75rem; align-items: stretch; }

        .vd-btn {
          height: 46px; padding: 0 1.25rem; border-radius: var(--r-sm);
          font-weight: 700; font-size: 0.8125rem; font-family: 'Inter', sans-serif;
          display: inline-flex; align-items: center; justify-content: center; gap: 0.5rem;
          cursor: pointer; border: 1px solid transparent; transition: all 0.18s ease;
          white-space: nowrap;
        }
        .vd-btn-ghost { background: rgba(255,255,255,0.04); border-color: var(--border2); color: var(--text); }
        .vd-btn-ghost:hover { background: rgba(255,255,255,0.09); }
        .vd-btn-teal {
          background: rgba(0,229,195,0.1); border-color: rgba(0,229,195,0.22); color: var(--teal);
        }
        .vd-btn-teal:hover { background: rgba(0,229,195,0.18); }

        .vd-active-chip {
          height: 46px; padding: 0 1.25rem; border-radius: var(--r-sm);
          background: rgba(0,229,195,0.1); border: 1px solid rgba(0,229,195,0.22);
          color: var(--teal); font-weight: 700; font-size: 0.8125rem;
          display: inline-flex; align-items: center; gap: 0.5rem; white-space: nowrap;
        }

        .vd-spin { animation: vd-spin 1s linear infinite; }
        @keyframes vd-spin { to { transform: rotate(360deg); } }

        /* ── Panel base ── */
        .vd-panel {
          background: var(--surface); border: 1px solid var(--border);
          border-radius: var(--r-lg); box-shadow: var(--shadow);
          padding: 1.75rem; transition: border-color 0.2s;
        }
        .vd-panel:hover { border-color: var(--border2); }

        /* ── Mobile AI panel ── */
        .vd-mobile-panel {
          margin-bottom: 1.75rem;
          background: rgba(139,92,246,0.07);
          border-color: rgba(139,92,246,0.2);
        }
        .vd-mobile-row { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 1.25rem; }
        .vd-mobile-head { display: flex; align-items: center; gap: 1rem; }
        .vd-mobile-icon {
          width: 52px; height: 52px; border-radius: var(--r); flex-shrink: 0;
          background: rgba(139,92,246,0.14); border: 1px solid rgba(139,92,246,0.25);
          color: #A78BFA; display: flex; align-items: center; justify-content: center;
        }
        .vd-mobile-title { font-size: 1.0625rem; font-weight: 800; color: var(--text); margin: 0 0 0.25rem; }
        .vd-mobile-sub { font-size: 0.8125rem; color: #C4B5FD; margin: 0; }
        .vd-mini-ai-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 0.625rem; }
        @media (min-width: 700px) { .vd-mini-ai-grid { grid-template-columns: repeat(4, 1fr); } }

        .vd-mini-ai-card {
          background: rgba(255,255,255,0.04); border: 1px solid var(--border2);
          border-radius: var(--r-sm); padding: 0.75rem 1rem;
        }
        .vd-mini-ai-title { font-size: 0.6875rem; color: var(--muted); margin: 0 0 0.25rem; }
        .vd-mini-ai-value { font-size: 0.9375rem; font-weight: 800; color: var(--text); margin: 0; }

        /* ── Main grid ── */
        .vd-main-grid { display: grid; grid-template-columns: 1fr; gap: 1.75rem; }
        @media (min-width: 1280px) { .vd-main-grid { grid-template-columns: repeat(2, 1fr); } }

        /* ── Panel head ── */
        .vd-panel-head { display: flex; align-items: center; gap: 0.875rem; margin-bottom: 1.75rem; }
        .vd-panel-head-icon {
          width: 52px; height: 52px; border-radius: var(--r); display: flex;
          align-items: center; justify-content: center; flex-shrink: 0;
        }
        .vd-panel-title { font-size: 1.375rem; font-weight: 800; color: var(--text); margin: 0 0 0.25rem; }
        .vd-panel-sub { font-size: 0.8125rem; color: var(--muted); margin: 0; }

        /* ── Field / select ── */
        .vd-field { margin-bottom: 1.5rem; }
        .vd-field-label { display: block; font-size: 0.8125rem; color: var(--muted); margin-bottom: 0.625rem; }
        .vd-select {
          width: 100%; height: 50px; border-radius: var(--r-sm);
          background: rgba(255,255,255,0.04); border: 1px solid var(--border2);
          padding: 0 1rem; color: var(--text); font-size: 0.9375rem;
          outline: none; transition: border-color 0.18s; font-family: inherit;
        }
        .vd-select:focus { border-color: rgba(29,110,255,0.5); }
        .vd-select option { background: #0D1733; color: var(--text); }

        /* ── Dropzone ── */
        .vd-dropzone {
          position: relative; border-radius: var(--r-lg); border: 2px dashed var(--border2);
          background: rgba(255,255,255,0.025); padding: 2.5rem 1.75rem; text-align: center;
          transition: all 0.2s;
        }
        .vd-dropzone-active { border-color: rgba(29,110,255,0.55); background: rgba(29,110,255,0.07); }
        .vd-dropzone-icon {
          width: 84px; height: 84px; border-radius: var(--r-lg); margin: 0 auto 1.5rem;
          background: rgba(29,110,255,0.12); border: 1px solid rgba(29,110,255,0.22);
          color: #6AA3FF; display: flex; align-items: center; justify-content: center;
        }
        .vd-dropzone-title { font-size: 1.375rem; font-weight: 800; color: var(--text); margin: 0 0 0.75rem; }
        .vd-dropzone-sub { font-size: 0.875rem; color: var(--muted); max-width: 380px; margin: 0 auto 1.5rem; line-height: 1.55; }
        .vd-hidden-input { display: none; }
        .vd-choose-btn {
          display: inline-flex; align-items: center; justify-content: center; gap: 0.5rem;
          height: 46px; padding: 0 1.5rem; border-radius: var(--r-sm);
          background: linear-gradient(120deg, var(--blue), var(--violet));
          color: #fff; font-weight: 700; font-size: 0.875rem; cursor: pointer;
          transition: opacity 0.18s;
        }
        .vd-choose-btn:hover { opacity: 0.88; }

        .vd-file-card {
          margin-top: 1.5rem; text-align: left; border-radius: var(--r);
          border: 1px solid rgba(0,229,195,0.22); background: rgba(0,229,195,0.08);
          padding: 1rem;
        }
        .vd-file-card-row { display: flex; align-items: center; gap: 0.75rem; }
        .vd-file-card-check { color: var(--teal); flex-shrink: 0; }
        .vd-file-card-info { flex: 1; min-width: 0; }
        .vd-file-card-name { font-weight: 700; color: var(--text); margin: 0; word-break: break-all; font-size: 0.875rem; }
        .vd-file-card-meta { font-size: 0.8125rem; color: var(--teal); margin: 0.2rem 0 0; }
        .vd-file-card-actions { display: grid; grid-template-columns: repeat(2, 1fr); gap: 0.625rem; margin-top: 1rem; }
        .vd-mini-btn {
          height: 38px; border-radius: var(--r-sm); font-weight: 700; font-size: 0.8125rem;
          display: flex; align-items: center; justify-content: center; gap: 0.4rem;
          cursor: pointer; border: 1px solid; transition: background 0.15s; font-family: inherit;
        }
        .vd-mini-btn-blue { background: rgba(29,110,255,0.1); border-color: rgba(29,110,255,0.22); color: #6AA3FF; }
        .vd-mini-btn-blue:hover { background: rgba(29,110,255,0.18); }
        .vd-mini-btn-red { background: rgba(239,68,68,0.1); border-color: rgba(239,68,68,0.22); color: #F87171; }
        .vd-mini-btn-red:hover { background: rgba(239,68,68,0.18); }

        /* ── Verify button ── */
        .vd-verify-btn {
          width: 100%; height: 54px; margin-top: 1.75rem; border-radius: var(--r);
          background: linear-gradient(120deg, var(--blue), var(--violet));
          color: #fff; font-weight: 800; font-size: 0.9375rem; border: none;
          display: flex; align-items: center; justify-content: center; gap: 0.75rem;
          cursor: pointer; transition: opacity 0.2s, transform 0.2s;
        }
        .vd-verify-btn:hover:not(:disabled) { opacity: 0.9; transform: translateY(-1px); }
        .vd-verify-btn:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }
        .vd-loader {
          width: 18px; height: 18px; border-radius: 50%;
          border: 2px solid rgba(255,255,255,0.3); border-top-color: #fff;
          animation: vd-spin 0.8s linear infinite;
        }

        /* ── Result column ── */
        .vd-result-col { display: flex; flex-direction: column; gap: 1.75rem; }

        .vd-result-head { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 1.25rem; margin-bottom: 1.75rem; }
        .vd-result-head-left { display: flex; align-items: center; gap: 1rem; }
        .vd-result-head-icon {
          width: 60px; height: 60px; border-radius: var(--r-lg);
          background: rgba(0,229,195,0.12); border: 1px solid rgba(0,229,195,0.22);
          color: var(--teal); display: flex; align-items: center; justify-content: center; flex-shrink: 0;
        }
        .vd-result-title { font-size: 1.625rem; font-weight: 800; color: var(--text); margin: 0 0 0.25rem; }
        .vd-result-sub { font-size: 0.875rem; color: var(--teal); margin: 0; }
        .vd-result-actions { display: flex; gap: 0.625rem; }
        .vd-icon-btn {
          width: 40px; height: 40px; border-radius: var(--r-sm);
          background: rgba(255,255,255,0.04); border: 1px solid var(--border2);
          color: var(--text); display: flex; align-items: center; justify-content: center;
          cursor: pointer; transition: background 0.15s;
        }
        .vd-icon-btn:hover { background: rgba(255,255,255,0.1); }
        .vd-icon-btn-red { background: rgba(239,68,68,0.1); border-color: rgba(239,68,68,0.22); color: #F87171; }
        .vd-icon-btn-red:hover { background: rgba(239,68,68,0.18); }

        /* ── Decision banner ── */
        .vd-decision-banner {
          border-radius: var(--r); border: 1px solid; padding: 1.125rem 1.25rem;
          margin-bottom: 1.75rem; display: flex; align-items: center; gap: 0.875rem;
        }
        .vd-decision-verified { background: rgba(0,229,195,0.08); border-color: rgba(0,229,195,0.2); color: var(--teal); }
        .vd-decision-rejected { background: rgba(239,68,68,0.08); border-color: rgba(239,68,68,0.2); color: #F87171; }
        .vd-decision-pending  { background: rgba(245,158,11,0.08); border-color: rgba(245,158,11,0.2); color: var(--amber); }
        .vd-decision-label { font-size: 0.8125rem; color: var(--muted); margin: 0 0 0.2rem; }
        .vd-decision-value { font-size: 1.375rem; font-weight: 800; margin: 0; }

        /* ── Metric row ── */
        .vd-metric-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0.875rem; margin-bottom: 1.75rem; }
        .vd-metric-box {
          background: rgba(255,255,255,0.03); border: 1px solid var(--border);
          border-radius: var(--r); padding: 1.125rem;
        }
        .vd-metric-box-icon {
          width: 40px; height: 40px; border-radius: 10px;
          display: flex; align-items: center; justify-content: center; margin-bottom: 0.875rem;
        }
        .vd-metric-box-title { font-size: 0.75rem; color: var(--muted); margin: 0 0 0.375rem; }
        .vd-metric-box-value { font-family: 'DM Mono', monospace; font-size: 1.625rem; font-weight: 500; color: var(--text); margin: 0; }

        /* ── Recommendation ── */
        .vd-recommend-box {
          border-radius: var(--r); border: 1px solid; padding: 1.25rem 1.5rem;
          margin-bottom: 1.75rem; display: flex; gap: 1rem; align-items: flex-start;
        }
        .vd-recommend-teal  { background: rgba(0,229,195,0.08); border-color: rgba(0,229,195,0.2); color: var(--teal); }
        .vd-recommend-amber { background: rgba(245,158,11,0.08); border-color: rgba(245,158,11,0.2); color: var(--amber); }
        .vd-recommend-red   { background: rgba(239,68,68,0.08); border-color: rgba(239,68,68,0.2); color: #F87171; }
        .vd-recommend-label-sm { font-size: 0.8125rem; color: var(--muted); margin: 0 0 0.25rem; }
        .vd-recommend-label { font-size: 1.625rem; font-weight: 800; margin: 0; }
        .vd-recommend-desc { color: var(--text); opacity: 0.85; margin: 0.625rem 0 0; line-height: 1.55; font-size: 0.875rem; }

        /* ── Checklist ── */
        .vd-checklist-block {
          border-radius: var(--r); border: 1px solid var(--border);
          background: rgba(255,255,255,0.025); padding: 1.375rem; margin-bottom: 1.75rem;
        }
        .vd-checklist-title {
          display: flex; align-items: center; gap: 0.625rem;
          font-size: 1.0625rem; font-weight: 800; color: var(--text); margin: 0 0 1.125rem;
        }
        .vd-checklist-list { display: flex; flex-direction: column; gap: 0.625rem; }
        .vd-checklist-item {
          display: flex; align-items: flex-start; gap: 0.75rem;
          background: rgba(255,255,255,0.03); border: 1px solid var(--border);
          border-radius: var(--r-sm); padding: 0.875rem 1rem;
        }
        .vd-checklist-item-label { color: var(--text); font-weight: 700; margin: 0; font-size: 0.875rem; }
        .vd-checklist-item-note { color: var(--muted); font-size: 0.8125rem; margin: 0.25rem 0 0; }

        /* ── Admin box ── */
        .vd-admin-box {
          border-radius: var(--r); border: 1px solid; padding: 1.125rem 1.25rem;
          margin-bottom: 1.75rem; display: flex; align-items: center; gap: 0.875rem;
        }
        .vd-admin-warn { background: rgba(245,158,11,0.08); border-color: rgba(245,158,11,0.2); color: var(--amber); }
        .vd-admin-ok   { background: rgba(0,229,195,0.08); border-color: rgba(0,229,195,0.2); color: var(--teal); }
        .vd-admin-title { color: var(--text); font-weight: 800; margin: 0 0 0.2rem; font-size: 0.9375rem; }
        .vd-admin-sub { margin: 0; font-size: 0.8125rem; opacity: 0.9; }

        /* ── Extracted info ── */
        .vd-extracted-block { border-radius: var(--r); border: 1px solid var(--border); background: rgba(255,255,255,0.025); overflow: hidden; }
        .vd-extracted-head { display: flex; align-items: center; gap: 0.625rem; padding: 1.25rem 1.375rem; border-bottom: 1px solid var(--border); }
        .vd-extracted-title { font-size: 1.0625rem; font-weight: 800; color: var(--text); margin: 0; }
        .vd-extracted-list { display: flex; flex-direction: column; }
        .vd-extracted-row {
          width: 100%; display: flex; align-items: flex-start; justify-content: space-between;
          gap: 1.25rem; padding: 1rem 1.375rem; border-bottom: 1px solid var(--border);
          background: none; border-left: none; border-right: none; border-top: none;
          cursor: pointer; text-align: left; transition: background 0.15s; font-family: inherit;
        }
        .vd-extracted-row:last-child { border-bottom: none; }
        .vd-extracted-row:hover { background: rgba(255,255,255,0.035); }
        .vd-extracted-key { color: var(--muted); font-size: 0.8125rem; min-width: 160px; text-transform: capitalize; }
        .vd-extracted-value { color: var(--text); font-weight: 700; text-align: right; white-space: pre-wrap; word-break: break-word; font-size: 0.875rem; }

        /* ── Engine panel ── */
        .vd-engine-panel { background: rgba(29,110,255,0.06); border-color: rgba(29,110,255,0.2); }
        .vd-engine-head { display: flex; align-items: center; gap: 1rem; margin-bottom: 1.5rem; }
        .vd-engine-title { font-size: 1.25rem; font-weight: 800; color: var(--text); margin: 0 0 0.25rem; }
        .vd-engine-sub { font-size: 0.8125rem; color: #9DBDFF; margin: 0; }
        .vd-ai-status-list { display: flex; flex-direction: column; gap: 0.625rem; }
        .vd-ai-status-row {
          display: flex; align-items: center; justify-content: space-between; gap: 1rem;
          background: rgba(255,255,255,0.03); border: 1px solid var(--border);
          border-radius: var(--r-sm); padding: 0.875rem 1rem;
        }
        .vd-ai-status-label { color: var(--text); font-size: 0.875rem; }
        .vd-ai-status-value { color: var(--teal); font-weight: 700; text-align: right; font-size: 0.8125rem; }

        /* ── Empty panel ── */
        .vd-empty-panel {
          display: flex; flex-direction: column; align-items: center; justify-content: center;
          text-align: center; padding: 3.5rem 2rem; min-height: 460px;
        }
        .vd-empty-icon {
          width: 96px; height: 96px; border-radius: var(--r-lg); margin-bottom: 1.75rem;
          background: rgba(255,255,255,0.04); border: 1px solid var(--border2);
          color: var(--muted); display: flex; align-items: center; justify-content: center;
        }
        .vd-empty-title { font-size: 1.625rem; font-weight: 800; color: var(--text); margin: 0 0 0.875rem; }
        .vd-empty-sub { color: var(--muted); max-width: 380px; margin: 0; line-height: 1.55; }

        /* ── Shared icon color helpers ── */
        .vd-icon-blue   { background: rgba(29,110,255,0.14); color: #6AA3FF; }
        .vd-icon-amber  { background: rgba(245,158,11,0.14); color: #FBB040; }
        .vd-icon-teal   { background: rgba(0,229,195,0.12);  color: var(--teal); }
        .vd-icon-red    { background: rgba(239,68,68,0.14);  color: #F87171; }
        .vd-icon-violet { background: rgba(139,92,246,0.14); color: #A78BFA; }

        @media (prefers-reduced-motion: reduce) {
          *, *::before, *::after { animation-duration: 0.01ms !important; transition-duration: 0.01ms !important; }
        }
      `}</style>
    </div>
  );
}

/* ─────────────────────────────────────────
   Presentational pieces
───────────────────────────────────────── */
function DecisionBanner({ status, label }) {
  const config = {
    verified: { icon: CheckCircle, cls: "vd-decision-verified" },
    rejected: { icon: XCircle, cls: "vd-decision-rejected" },
    "pending review": { icon: Clock, cls: "vd-decision-pending" },
  };

  const current = config[status] || config["pending review"];
  const Icon = current.icon;

  return (
    <div className={`vd-decision-banner ${current.cls}`}>
      <Icon size={24} />
      <div>
        <p className="vd-decision-label">Final Verification Decision</p>
        <h3 className="vd-decision-value">{label}</h3>
      </div>
    </div>
  );
}

function RecommendationCard({ recommendation }) {
  if (!recommendation) return null;

  const styleMap = {
    green: { cls: "vd-recommend-teal", icon: CheckCircle },
    teal: { cls: "vd-recommend-teal", icon: CheckCircle },
    yellow: { cls: "vd-recommend-amber", icon: AlertTriangle },
    amber: { cls: "vd-recommend-amber", icon: AlertTriangle },
    red: { cls: "vd-recommend-red", icon: XCircle },
  };

  const current = styleMap[recommendation.color] || styleMap.amber;
  const Icon = current.icon;

  return (
    <div className={`vd-recommend-box ${current.cls}`}>
      <Icon size={26} />
      <div>
        <p className="vd-recommend-label-sm">AI Recommendation</p>
        <h3 className="vd-recommend-label">{recommendation.label}</h3>
        <p className="vd-recommend-desc">{recommendation.description}</p>
      </div>
    </div>
  );
}

function ChecklistCard({ checklist }) {
  if (!checklist || checklist.length === 0) return null;

  return (
    <div className="vd-checklist-block">
      <h3 className="vd-checklist-title">
        <CheckCircle2 size={20} color="#6AA3FF" />
        Verification Checklist
      </h3>

      <div className="vd-checklist-list">
        {checklist.map((item, index) => (
          <div key={`${item.label}-${index}`} className="vd-checklist-item">
            {item.passed ? (
              <CheckCircle2 size={18} color="#00E5C3" style={{ marginTop: 2, flexShrink: 0 }} />
            ) : (
              <AlertTriangle size={18} color="#F59E0B" style={{ marginTop: 2, flexShrink: 0 }} />
            )}

            <div>
              <p className="vd-checklist-item-label">{item.label}</p>
              {item.note && <p className="vd-checklist-item-note">{item.note}</p>}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function MetricCard({ title, value, color }) {
  return (
    <div className="vd-metric-box">
      <div className={`vd-metric-box-icon vd-icon-${color}`}>
        <ShieldCheck size={18} />
      </div>
      <p className="vd-metric-box-title">{title}</p>
      <p className="vd-metric-box-value">{value}</p>
    </div>
  );
}

function AIStatus({ title, status }) {
  return (
    <div className="vd-ai-status-row">
      <span className="vd-ai-status-label">{title}</span>
      <span className="vd-ai-status-value">{status}</span>
    </div>
  );
}

function MiniAICard({ title, value }) {
  return (
    <div className="vd-mini-ai-card">
      <p className="vd-mini-ai-title">{title}</p>
      <h3 className="vd-mini-ai-value">{value}</h3>
    </div>
  );
}